site_name: zighelp.org
repo_url: https://github.com/zighelp/zighelp/

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      title: " "
      permalink: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.indexes

nav:
  - Home: README.md
  - Chapter 0 - Getting Started: chapter-0.md
  - Chapter 1 - Basics: chapter-1.md
  - Chapter 2 - Standard Patterns: chapter-2.md
  - Chapter 3 - Build system: chapter-3.md
  - Chapter 4 - Working with C: chapter-4.md
  - Chapter 5 - Async: chapter-5.md
