site_name: zighelp.org
repo_url: https://github.com/zighelp/zighelp/
repo_name: zighelp/zighelp

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      title: " "
      permalink: true

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/images/logo.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: zighelp
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: zighelp
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.indexes
    - navigation.footer
    - content.action.edit
    - content.action.view

nav:
  - Home: README.md
  - Chapter 0 - Getting Started: chapter-0.md
  - Chapter 1 - Basics: chapter-1.md
  - Chapter 2 - Standard Patterns: chapter-2.md
  - Chapter 3 - Build system: chapter-3.md
  - Chapter 4 - Working with C: chapter-4.md
  - Chapter 5 - Async: chapter-5.md
